server:
  port: 8080
  error:
    include-message: always

spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: create-drop
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true

external:
  api:
    multi-url: https://min-api.cryptocompare.com/data/pricemulti?fsyms={fsyms}&tsyms={tsyms}
    single-url: https://min-api.cryptocompare.com/data/price?fsym={fsym}&tsyms={tsyms}

java:
  runtime:
    version: 11